### PR TITLE
Support for Linux and SwiftPM by @AmmonP

### PR DESCRIPTION
**Pull request by SKarajic**

### CODE REVIEW

**Comment by Kelmatou** [comment]
Hi @SKarajic!

I reviewed @AmmonP's improvement and I like it.
The pipeline is failing because the Xcode project file doesn't reference the new LAPIImage.swift

I'll update the code to make it work on Apple's platforms as well

Thank you

**Comment by SKarajic** [comment]
Yeah, would be great if it could be adjusted. This change would also allow for server-side development. I noticed @AmmonP's fork, but noticed that he didn't create a PR, so i did instead. If i notice anything not working on server-side, i'll happily create some changes in order to make it work. 👍🏻

**Comment by Kelmatou** [comment]
I'd appreciate any feedback on server-side usage!

I've changed the PR destination to a specific branch. I'll fix the compile errors and I will merge it into master
Thanks @SKarajic @AmmonP!

**Comment by AmmonP** [comment]
If you need me to look at anything let me know, I was just originally making rudimentary adjustments to get it to compile. My biggest concern was to avoid breaking the existing API definitions.

**Pull request merged**
